### ISSUE TITLE
configure monit for email delivery

### ISSUE THREAD

**Issue by noha** [noha/virtual-gemstone#12]
Monit is configured to restart things on its own. If there is a bigger problem it can report it via email. This probably needs to go into a appliance-wide admin email address that can be added

**Comment by mostalive** [comment]
I've been thinking about this (it was once almost in the source). It also needs a default / configurable mailserver configuration (that has to go in the main monit file). I've got it set up for one of my production boxes, works well. It seemed to work on vagrant as well, monit doesn't seem to mind too much if you say the mailserver is 'localhost' and there is no smtp server there...

The other way to do it is have conditionals in the main monit template, and only output the mailserver and the default address if they are set in the configuration.

**Comment by noha** [comment]
I don't think there is a need to incude a mailserver in the appliance. We don't need to receive mail and the configuration is complex in any case. Usually you use a package like ssmtp that is configurable which mailhub it should use. You can then send emails like normal using mail,... whatever

**Comment by mostalive** [comment]
Doing a spike, it seemed to make no difference whether there was a
mailserver or not for monit - you can say 'localhost' is the mailserver,
and it will just silently fail or something...

On Tue, 13 Mar 2012 03:56:11 -0700, Norbert Hartl
reply@reply.github.com
wrote:

> I don't think there is a need to incude a mailserver in the
> appliance. We don't need to receive mail and the configuration is
> complex in any case. Usually you use a package like ssmtp that is
> configurable which mailhub it should use. You can then send emails
> like normal using mail,... whatever
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noha/virtual-gemstone/issues/12#issuecomment-4471030

## 

Willem van den Ende
Living Software is a partner in QWAN

**Comment by noha** [comment]
The main objective here is IMHO not fail silently but to be able to add a relay mailhub to the appliance so that the mails generated in the system can be forwarded. Same goes for syslog
