### ISSUE TITLE
nginx support for file upload progress

### ISSUE THREAD

**Issue by mostalive** [noha/virtual-gemstone#18]
We use the file upload progress module. The current versions of nginx-full or nginx-extra in ubuntu11.04 do not support it. 

Therefore we have compiled it by hand. 
Current state: it compiles from a shell script
Desired state: include a modified version of opscode-nginx cookbook, which succesfully compiles nginx from source, but with very few modules downloaded. (it's on willem's laptop, found it on github somewhere ;)), with its two dependencies build-utils and runit. The opscode cookbook installs the necessary libraries (now also included on top of our shell script).

here's the shell script:
# based on http://thekindofme.wordpress.com/2010/11/19/ubuntu-10-04-nginx-with-upload-and-upload-progress-modules-rvm-postgresql/
# and http://wiki.nginx.org/Modules for the ssl magic
# installs and runs (don't know how to stop ;) ). reports OpenSSL present and used by a couple of things.

sudo apt-get install build-essential
sudo apt-get install libpcre3 libpcre3-dev libssl-dev
wget http://nginx.org/download/nginx-0.8.54.tar.gz
tar xzf nginx-0.8.54.tar.gz
wget --no-check-certificate https://github.com/masterzen/nginx-upload-progress-module/zipball/v0.8.2
mv v0.8.2 nginx-upload-progress-module-v0.8.2.zip
unzip nginx-upload-progress-module-v0.8.2.zip
wget --no-check-certificate https://github.com/gnosek/nginx-upstream-fair/zipball/master
mv master nginx-upstream-fair.zip
unzip nginx-upstream-fair.zip
wget http://www.grid.net.ru/nginx/download/nginx_upload_module-2.2.0.tar.gz
tar zxf nginx_upload_module-2.2.0.tar.gz
cd nginx-0.8.54
./configure --add-module=../gnosek-nginx-upstream-fair-2131c73 --add-module=../masterzen-nginx-upload-progress-module-8b55a34/ --add-module=../nginx_upload_module-2.2.0/ --with-http_ssl_module --with-http_flv_module   --with-http_gzip_static_module 
make
sudo make install

**Comment by noha** [comment]
What are the main differences between the opscode nginx recipe and your stuff? How to proceed? Will you integrate it? That would be fine

**Comment by mostalive** [comment]
I Will integrate it. Opscodes recipe has build from source starting point.

"Norbert Hartl" reply@reply.github.com wrote:

> What are the main differences between the opscode nginx recipe and your stuff? How to proceed? Will you integrate it? That would be fine
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noha/virtual-gemstone/issues/18#issuecomment-2153976

## 

+31 6 413 06 965
Sent mobile with K-9 Mail. Pls xcuse my brevity.

**Comment by mostalive** [comment]
Main differences: downloading of needed upload-progress and upstream-fair module, providing the necessary compilation switches to make it work.

**Comment by mostalive** [comment]
integration test with demo app for the next milestone, separate issue, so we can close this mega one.
