### ISSUE TITLE
gemstone library: check environment is set up properly

### ISSUE THREAD

**Issue by noha** [noha/virtual-gemstone#28]
The communication to gemstone is done via the topaz commandline utility. The usage is wrapped inside a library of the gemstone cookbook. We need to make sure that the proper environment ist sourced when using the library. Hardcoding the path for topaz is not feasible as there should a possibility to install different versions of gemstone and therefor the topaz binary should be taken from the right installed version

**Comment by mostalive** [comment]
This seemed to be fixed after doing a clean build. Sourcing the topaz location from /etc/gemstone/stones.d seemed to work.
