### ISSUE TITLE
loading new seaside does not load fast cgi

### ISSUE THREAD

**Issue by noha** [noha/virtual-gemstone#31]
The new configuration of seaside30 does not include loading of fast cgi. The setup is nailed to the usage of fast cgi. So it is needed to add

ConfigurationOfSeaside30 project lastVersion load: #( 'FastCGI' 'Seaside-Adaptors-FastCGI')

to the end of loading seaside in order to have the adaptor in place

**Comment by mostalive** [comment]
should be closeable after pull request (#32). Hadn't seen this, also don't know if I can attach code to it (should be possible).
