### ISSUE TITLE
Automated end-to-end tests

### ISSUE THREAD

**Issue by mostalive** [noha/virtual-gemstone#36]
I'd like to use rspec for this. Cucumber seems popular amongst devops, but since we are our customer, the extra overhead of parsing plain text is probably not worth it.

Starts to be needed since we now have e.g. http on two ports instead of one. We have monitoring inside the vm, but that does not fail the build (might also be an option - check monit status from jenkins so we keep DRY).

**Comment by noha** [comment]
can you elaborate on this? I'm not sure I understand what you are going to test. Is it the services on the machine? If so it would be cool but also hard.

**Comment by mostalive** [comment]
first the outside (http / https - is seaside there). On the inside is
doable with ruby's net:ssh library, I can dig up an example later, but
have to run now... So you could run tests on the inside as well and get
a report from that, or use net:ssh in tests from the outside with some
probes. But my guess is the latter is going to be slow.

Basically, at the moment I would like to know: I've messed with the
nginx recipe, is seaside still visible?

Cheers,

Willem

On Wed, 25 Jan 2012 05:40:11 -0800, Norbert Hartl
reply@reply.github.com
wrote:

> can you elaborate on this? I'm not sure I understand what you are
> going to test. Is it the services on the machine? If so it would be
> cool but also hard.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noha/virtual-gemstone/issues/36#issuecomment-3650617

## 

Willem van den Ende
Living Software is a partner in QWAN

**Comment by noha** [comment]
Ok, sounds perfect. So we work towards a spec of a machine with recipes and can test the machine to the spec. That's good.

**Comment by mostalive** [comment]
Just realized I can probably close the file upload one. That can only be tested when there is an application behind it that does file upload... Maybe I should ask stephan to isolate the file upload stuff in their application, so we can add it as a sample application in seaside, and then write a spec for it?

Willem

On Jan 25, 2012, at 2:56 PM, Norbert Hartl wrote:

> Ok, sounds perfect. So we work towards a spec of a machine with recipes and can test the machine to the spec. That's good.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noha/virtual-gemstone/issues/36#issuecomment-3650888

Willem van den Ende
willem@livingsoftware.nl - 06 413 06 965 - blog: http://me.andering.com
Living Software is a partner in QWAN - www.qwan.it

**Comment by noha** [comment]
Well, then you can't close it :) Let's just move it out of this milestone and make it separate from the nginx mega task

**Comment by mostalive** [comment]
Ok

"Norbert Hartl" reply@reply.github.com wrote:

> Well, then you can't close it :) Let's just move it out of this milestone and make it separate from the nginx mega task
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noha/virtual-gemstone/issues/36#issuecomment-3651030

## 

+31 6 413 06 965
Sent mobile with K-9 Mail. Pls xcuse my brevity.

**Comment by mostalive** [comment]
forgot to close the last time
