### ISSUE TITLE
Ruby errors on "vagrant up"

### ISSUE THREAD

**Issue by ccrraaiigg** [noha/virtual-gemstone#38]
Hi--

```
 I get the following on "vagrant up":
```

/Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/config/vm.rb:44:in `to_s': wrong number of arguments (1 for 0) (ArgumentError)
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/config/vm.rb:44:in`forward_port'
    from /Users/craig/me/work/mcintosh/virtual-gemstone/vagrant/Vagrantfile:9
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:83:in `call'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:83:in`load'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:79:in `each'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:79:in`load'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:76:in `each'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:76:in`load'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/environment.rb:383:in `load_config!'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/environment.rb:388:in`call'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/environment.rb:388:in `load_config!'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/lib/vagrant/environment.rb:323:in`load!'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.0/bin/vagrant:40
    from /usr/bin/vagrant:19:in `load'
    from /usr/bin/vagrant:19

```
 Help? Thanks!

 Craig Latta
 <craig@netjam.org>
```

**Comment by noha** [comment]
What ruby do you use? It is extremly annyoing that ruby comes in so many different installations. We have building our stuff using rvm (http://beginrescueend.com/rvm/install/). It is a bit cumbersome at first but then it works quite ok. I think we need to add some instructions to get ruby going in order to use our stuff. I'll open another ticket.

**Comment by ccrraaiigg** [comment]
Hi Norbert--

> What ruby do you use?

```
 Does the following answer that?
```

craig@rhythm vagrant 37> ruby --version

ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

craig@rhythm vagrant 38>

```
 thanks again,
```

-C

**Comment by noha** [comment]
Yes, it does. I'm not an ruby expert but your version seems to be the one that comes with Mac OS X. And it does not work with it. You might try to install the rvm ruby version in order to get it going. Sorry for the inconvenience

**Comment by ccrraaiigg** [comment]
> I'm not an ruby expert but your version seems to be the one that
> comes with Mac OS X. And it does not work with it. You might try to
> install the rvm ruby version in order to get it going. Sorry for the >
> inconvenience

```
 No worries, I'm amazed this works at all. :)  I started over, and
```

installed rvm ruby, but I end up with the same errors.

```
 thanks again,
```

-C

**Comment by noha** [comment]
I tried it myself and it seems you are using a new vagrant gem. Vagrant has changed the option format for port forwarding. I commited a change to the Vagrantfile that should fix it

**Comment by artm** [comment]
this happened to me when I tried to use an old box after having upgraded to vagrant 1.0.5 (sorry, I have no idea which was the previous version I used). I had to edit the file `~/.vagrant.d/boxes/<BOX_NAME>/include/_Vagrantfile` and change all `config.vm.forward_port “...”, NNN, NNN` to `config.vm.forward_port NNN, NNN`.
