### ISSUE TITLE
Parameters for vagrant configurable per user and job

### ISSUE THREAD

**Issue by mostalive** [noha/virtual-gemstone#42]
We want to be able to configure per user, and per jenkins job:
- name of the vagrant box
- which ports to forward: 
  with multiple jenkins jobs using the same ports as a development vm on the same machine we need separate ports to forward for web and the gemstone ports. For Jenkins I would be happy (as long as there are not yet end to end tests) to have no ports open at all. Ssh is configured automagically to be on a unique port
- cookbooks path - I sometimes have a mixed build where I try to simulate a production box by installing my own recipes that have nothing to do with virtual-gemstone

We now do this in the Vagrantfile. This is brittle, we have to be careful to commit only those lines that are not specific to our own configuration.

I made the vm name configurable in my vagrantfile through an environment variable like so:

  #e.g. "gemstone-ubuntu11.10-ruby192"
  gemstone_vm = ENV["gemstone_vm"]
  if (!gemstone_vm.nil? && !gemstone_vm.empty?  ) 
    config.vm.box = gemstone_vm
    #config.vm.memory_size = 1024
  else
    config.vm.box = "gemstone"
  end

I disabled ports like this:

  vagrant_env = ENV["vagrant_env"]
  if(vagrant_env.nil? || vagrant_env != "build")
    config.vm.forward_port(80,7778)
    config.vm.forward_port(50377, 50377)
    config.vm.forward_port(50378, 50378)
  end

individual ports would need their own parameters. So we would end up with a lot of environment variables. 

Another solution might be to remove the Vagrantfile from git, replace it with a Vagrantfile.example, so everyone can have their own Vagrantfile.

**Comment by noha** [comment]
We don't need the netldi ports when running in jenkins. This is just to be able to connect with gemtools. The http port we just need if there are test scripts running outside of the appliance. I would rather ruyn them from the inside on don't open any ports while running under jenkins
